Repository EDDiscovery/EDDiscovery, pull requests merged in 2018-12, with the labels that each got.

#2225 Partial Polish translation - from new fork
  EDDiscovery/Translations/polski-pl.tlf
  EDDiscovery/UserControls/translation-polski-uc.tlp
  EliteDangerous/EliteDangerous/translation-polski-ed.tlp
  EliteDangerous/JournalEvents/translation-polski-je.tlp
Labels: Translation

#2233 Feature/scangrid
  EDDiscovery/UserControls/UserControlScanGrid.cs
  EliteDangerous/EDSM/EDSMClass.cs
  EliteDangerous/JournalEvents/JournalScan.cs
Labels: Bug Fixed, Code Improvement

#2239 Feature/scangrid
  EDDiscovery/UserControls/UserControlScanGrid.Designer.cs
  EDDiscovery/UserControls/UserControlScanGrid.cs
  EDDiscovery/UserControls/UserControlScanGrid.resx
Labels: Bug Fixed, Code Improvement

#2251 Added a couple of checks for not null values for planet class
  EDDiscovery/UserControls/UserControlScanGrid.cs
Labels: Bug Fixed

#2255 Feature/scangrid
  EDDIcons/Controls/Controls.cs
  EDDIcons/Controls/ScanGrid/Belt.png
  EDDIcons/Controls/ScanGrid/Ring.png
  EDDIcons/EDDIcons.csproj
  EDDiscovery/EDDiscovery.csproj
  EDDiscovery/Properties/Resources.Designer.cs
  EDDiscovery/Properties/Resources.resx
  EDDiscovery/Resources/green_back.png
  EDDiscovery/UserControls/UserControlScanGrid.Designer.cs
  EDDiscovery/UserControls/UserControlScanGrid.cs
  EDDiscovery/UserControls/UserControlScanGrid.resx
Labels: Bug Fixed, Code Improvement
